name: diary_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  provider: ^6.1.1
  image_picker: ^1.2.0
  file_picker: ^10.3.1
  table_calendar: ^3.0.9
  path: ^1.8.3
  record: ^6.1.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.2
  http: ^1.2.0
  web_socket_channel: ^3.0.0
  audioplayers: ^6.1.0
  video_player: ^2.8.3
  chewie: ^1.7.4
  intl: ^0.19.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true



flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21